/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Campaigns } from "./Campaigns";
import { CampaignsCountArgs } from "./CampaignsCountArgs";
import { CampaignsFindManyArgs } from "./CampaignsFindManyArgs";
import { CampaignsFindUniqueArgs } from "./CampaignsFindUniqueArgs";
import { CreateCampaignsArgs } from "./CreateCampaignsArgs";
import { UpdateCampaignsArgs } from "./UpdateCampaignsArgs";
import { DeleteCampaignsArgs } from "./DeleteCampaignsArgs";
import { User } from "../../user/base/User";
import { CampaignsService } from "../campaigns.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Campaigns)
export class CampaignsResolverBase {
  constructor(
    protected readonly service: CampaignsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Campaigns",
    action: "read",
    possession: "any",
  })
  async _campaignsItemsMeta(
    @graphql.Args() args: CampaignsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Campaigns])
  @nestAccessControl.UseRoles({
    resource: "Campaigns",
    action: "read",
    possession: "any",
  })
  async campaignsItems(
    @graphql.Args() args: CampaignsFindManyArgs
  ): Promise<Campaigns[]> {
    return this.service.campaignsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Campaigns, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Campaigns",
    action: "read",
    possession: "own",
  })
  async campaigns(
    @graphql.Args() args: CampaignsFindUniqueArgs
  ): Promise<Campaigns | null> {
    const result = await this.service.campaigns(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Campaigns)
  @nestAccessControl.UseRoles({
    resource: "Campaigns",
    action: "create",
    possession: "any",
  })
  async createCampaigns(
    @graphql.Args() args: CreateCampaignsArgs
  ): Promise<Campaigns> {
    return await this.service.createCampaigns({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Campaigns)
  @nestAccessControl.UseRoles({
    resource: "Campaigns",
    action: "update",
    possession: "any",
  })
  async updateCampaigns(
    @graphql.Args() args: UpdateCampaignsArgs
  ): Promise<Campaigns | null> {
    try {
      return await this.service.updateCampaigns({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Campaigns)
  @nestAccessControl.UseRoles({
    resource: "Campaigns",
    action: "delete",
    possession: "any",
  })
  async deleteCampaigns(
    @graphql.Args() args: DeleteCampaignsArgs
  ): Promise<Campaigns | null> {
    try {
      return await this.service.deleteCampaigns(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Campaigns): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
