/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CharactersService } from "../characters.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CharactersCreateInput } from "./CharactersCreateInput";
import { Characters } from "./Characters";
import { CharactersFindManyArgs } from "./CharactersFindManyArgs";
import { CharactersWhereUniqueInput } from "./CharactersWhereUniqueInput";
import { CharactersUpdateInput } from "./CharactersUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CharactersControllerBase {
  constructor(
    protected readonly service: CharactersService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Characters })
  @nestAccessControl.UseRoles({
    resource: "Characters",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCharacters(
    @common.Body() data: CharactersCreateInput
  ): Promise<Characters> {
    return await this.service.createCharacters({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        classField: true,
        createdAt: true,
        id: true,
        level: true,
        race: true,
        stats: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Characters] })
  @ApiNestedQuery(CharactersFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Characters",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async charactersItems(@common.Req() request: Request): Promise<Characters[]> {
    const args = plainToClass(CharactersFindManyArgs, request.query);
    return this.service.charactersItems({
      ...args,
      select: {
        classField: true,
        createdAt: true,
        id: true,
        level: true,
        race: true,
        stats: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Characters })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Characters",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async characters(
    @common.Param() params: CharactersWhereUniqueInput
  ): Promise<Characters | null> {
    const result = await this.service.characters({
      where: params,
      select: {
        classField: true,
        createdAt: true,
        id: true,
        level: true,
        race: true,
        stats: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Characters })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Characters",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCharacters(
    @common.Param() params: CharactersWhereUniqueInput,
    @common.Body() data: CharactersUpdateInput
  ): Promise<Characters | null> {
    try {
      return await this.service.updateCharacters({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          classField: true,
          createdAt: true,
          id: true,
          level: true,
          race: true,
          stats: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Characters })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Characters",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCharacters(
    @common.Param() params: CharactersWhereUniqueInput
  ): Promise<Characters | null> {
    try {
      return await this.service.deleteCharacters({
        where: params,
        select: {
          classField: true,
          createdAt: true,
          id: true,
          level: true,
          race: true,
          stats: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
