/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CampaignsCreateNestedManyWithoutUsersInput } from "./CampaignsCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { CharactersCreateNestedManyWithoutUsersInput } from "./CharactersCreateNestedManyWithoutUsersInput";
import { MapsCreateNestedManyWithoutUsersInput } from "./MapsCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SessionsCreateNestedManyWithoutUsersInput } from "./SessionsCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CampaignsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CampaignsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CampaignsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  campaignsItems?: CampaignsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CharactersCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CharactersCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CharactersCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  charactersItems?: CharactersCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MapsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MapsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MapsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  mapsItems?: MapsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  role?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SessionsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SessionsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  sessionsItems?: SessionsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
